### ISSUE TITLE
[Feature Request] File logging

### ISSUE THREAD

**Issue by mte0** [localip/nitro-sniper#281]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

I think it would be great (and also a simple thing to implement) to have logging saved to files eg we have a log folder, invites.txt, nitro.txt, giveaway.txt with all info such as the server invite, message links, senders, time if it failed/succeeded etc

### How will this be beneficial to the sniper

people can see what servers get them the most nitro even if they dont check the sniper console 24/7 or if the bot restarts and clears console

### Please provide an example of usage of this feature

friend asks what servers you get the most nitro from, you check the logs folder and see
what servertype should i add my alts too? checks logs
dam theres hella giveaways in this discord i need the invite to join with my main! checks logs

**Comment by Craftzman7** [comment]
I'll start working on this
