### ISSUE TITLE
[Feature Request] Blacklist certain channels on the nitro sniper

### ISSUE THREAD

**Issue by BBubbleTea** [localip/nitro-sniper#350]
### Is your feature request related to a problem?

I would like for snip nitro but without some channel, can you make it have blacklist channel nitro snip. 

### Describe the solution you'd like

User can input blacklist id channel in config file

### How will this be beneficial to the sniper

some sniper is staff/mod of server. We give nitro to buyer but they can't faster than bot

### Please provide an example of usage of this feature

I was claimed the customer's nitro, so i must compensation this

**Comment by AvaneeshG** [comment]
## Describe the solution you'd like
User ~~can input blacklist id channel ~~ being able to input blacklisted channel names in config file

##...

Please don't make your issue too specific

**Comment by localip** [comment]
Closed in #369
