### ISSUE TITLE
[Feature Request] [feel free to yoink] check for rerolls

### ISSUE THREAD

**Issue by IShowLight-7777** [localip/nitro-sniper#373]
### Is your feature request related to a problem?

Actually maybe make it check the message before "congrats {me}" if it contains "reroll" and then dm the person instead of host

### Describe the solution you'd like

Dm the reroller instead of host

### How will this be beneficial to the sniper

Not getting users banned?

### Please provide an example of usage of this feature

Idk alot of nitro servers have rerollers

**Comment by localip** [comment]
Sadly i can't as the link isn't provided in the re-roll message.
