### ISSUE TITLE
UptimeRobot no longer supporting repl.it links

### ISSUE THREAD

**Issue by editsellar** [localip/nitro-sniper#380]
### Describe the bug

Hey all, just wanted to mention that UptimeRobot is no longer supporting repl.it links starting April 1 (Past already).

I was wondering if anyone knows any **free** alternatives to UptimeRobot or maybe even alternatives to replit?

### To Reproduce

Host repl.it links on UptimeRobot

### Expected behavior

It should've pinged my repl, instead it didn't.

### Please provide your snipers settings.

```javascript
doesnt matter
```

**Comment by Craftzman7** [comment]
This was an April fools joke done by uptime robot (Can't confirm)

**Comment by Shkeffy** [comment]
> ### Describe the bug
> Hey all, just wanted to mention that UptimeRobot is no longer supporting repl.it links starting April 1 (Past already).
> 
> I was wondering if anyone knows any **free** alternatives to UptimeRobot or maybe even alternatives to replit?
> 
> ### To Reproduce
> Host repl.it links on UptimeRobot
> 
> ### Expected behavior
> It should've pinged my repl, instead it didn't.
> 
> ### Please provide your snipers settings.
> ```js
> doesnt matter
> ```
> 
> ### What platform are you seeing the problem on?
> _No response_
> 
> ### Relevant log output if applicable.
> _No response_

https://freshping.io
