### ISSUE TITLE
[Feature Request] Idea Here

### ISSUE THREAD

**Issue by MaiSan9999** [localip/nitro-sniper#381]
### Is your feature request related to a problem?

Update Local Installation instruction? make more clear

### Describe the solution you'd like

Update Local Installation instruction? like make more clear

### How will this be beneficial to the sniper

Because im dumb

### Please provide an example of usage of this feature

![image](https://user-images.githubusercontent.com/89659009/163045172-756a438c-a70a-4cd4-ae8d-919f1ad7cfc5.png)
![image](https://user-images.githubusercontent.com/89659009/163045182-cd13c866-ec79-4cfb-85c5-117229031417.png)

**Comment by MaiSan9999** [comment]
high quality image btw.

**Comment by Craftzman7** [comment]
The link redirects, it wouldn't matter if it got changed.
