### ISSUE TITLE
[HELP] My token changes evertyime so i can't set sniper

### ISSUE THREAD

**Issue by coffep** [localip/nitro-sniper#398]
### Describe the bug

Hey,

I setup the sniper but when i turn off my discord or pc.The token changes automaticly so the discord sniper bot stop working 'error not valid token' can you please help me ? thank you!

### To Reproduce

.

### Expected behavior

.

### Please provide your snipers settings.

```javascript
.
```

**Comment by Craftzman7** [comment]
Huh my tokens lasted about 2 months now. Make sure the token doesn't start with "dW" because that's an encrypted token.

**Comment by coffep** [comment]
> Huh my tokens lasted about 2 months now. Make sure the token doesn't start with "dW" because that's an encrypted token.

I use this Object.values(webpackChunkdiscord_app.push([[Symbol()], {}, (e) => e.c])).find(e => e.exports?.getToken).exports.getToken() to get the token.And everytime the token changes...Can you please send me ur discord it will be faster to talk.I need help asap

**Comment by Craftzman7** [comment]
Not talking to you on Discord, that's a free account ban. To get your token open Discord in your browser and open developer tools and and go to local storage and filter for "token", then click the button in dev tools that resizes the page for mobile devices. Your token will show up in local storage.

**Comment by coffep** [comment]
> Not talking to you on Discord, that's a free account ban. To get your token open Discord in your browser and open developer tools and and go to local storage and filter for "token", then click the button in dev tools that resizes the page for mobile devices. Your token will show up in local storage.

that's exactly what I do.And my token changes everytime after that i tried the other method with the code to console and same issue.I need to updates any settings on discord or what ? maybe discord made a new update??

**Comment by Craftzman7** [comment]
Unless you're signing in on a new device or changing your password then your token shouldn't be changing. No one else has seen this before.

**Comment by Craftzman7** [comment]
@localip not something we can really fix. You can probably close this now.
