### ISSUE TITLE
[Bug] I found a 'bug' If im not wrong.

### ISSUE THREAD

**Issue by coffep** [localip/nitro-sniper#401]
### Describe the bug

so when I have discord on which I want to snipe discord nitro I copy the token and paste it into sniper it works but if I turn off sniper and I logout from discord then when I turn on sniper I get an error Couldn't log into main account meaning sniping is not possible. Exiting process...
exit status 255.When I log back on discord the token changes is this normal?

### To Reproduce

f

### Expected behavior

f

### Please provide your snipers settings.

```javascript
f
```

**Comment by Craftzman7** [comment]
See #398

**Comment by Craftzman7** [comment]
@localip duplicate issue.
