### ISSUE TITLE
[Feature Request] Heroku bypass

### ISSUE THREAD

**Issue by josesilveiraa** [localip/nitro-sniper#402]
### Is your feature request related to a problem?

I would like to deploy it on Heroku. Heroku blocked it.

### Describe the solution you'd like

There's a kind of "bypass". Heroku blocks the repo URL, but if you fork it and deploy the sniper with your profile URL, it'll work flawlessy.

### How will this be beneficial to the sniper

Some users prefer to use Heroku over Repl.it because it's faster.

### Please provide an example of usage of this feature

It'd be used in the deployment steps.

**Comment by Craftzman7** [comment]
Heroku started banning forks, highly doubt this would be added back.

**Comment by josesilveiraa** [comment]
> Heroku started banning forks, highly doubt this would be added back.

Well, I think they can detect it by the name, so it could be just fine if you create a random name repo and push the files to this repo.  A code-based detection would be too much, wouldn't it?

**Comment by localip** [comment]
Sadly not possible, I've tried many times before.

**Comment by josesilveiraa** [comment]
> 

even the repo with another name?

**Comment by Craftzman7** [comment]
Yep, localip used to have automated repo name changes but it never worked.
