### ISSUE TITLE
Discord Webhooks

### ISSUE THREAD

**Issue by MxntyButDiff** [localip/nitro-sniper#414]
### Is your feature request related to a problem?

Is it possible to make the nitro sniper send the codes into a different webhook

Ex:

Invalid code To: https://discord.com/api/webhooks/95854577********/Bduo-**********************************/
Valid Code To: https://discord.com/api/webhooks/*************/**********************************/
Already Claimed: https://discord.com/api/webhooks/95854577********/Bduo-**********************************/

Would love if it's possible

### Describe the solution you'd like

.

### How will this be beneficial to the sniper

.

### Please provide an example of usage of this feature

.

**Comment by Craftzman7** [comment]
Ignore that, it's currently broken.
